add more spectral-cube class translators
glue-viz/glue-astronomy pull request #54
Opened 2021-11-06 15:05 UTC by keflavich

The `SpectralCube` handlers didn't work for any but the basic single-beam SpectralCube objects.  This adds support for the other types.

I haven't tested this extensively yet, but I think the ideas are sound - as long as the metadata is appropriately preserved.

Problem: `beams` needs to be subsetted along with the data.  How can we handle that?

2022-09-09 19:00 UTC, dhomeier commented
> Problem: `beams` needs to be subsetted along with the data. How can we handle that?

@keflavich does this need more work or could it be rebased to re-run the tests?

2022-09-12 13:33 UTC, dhomeier requested changes
The missing import and the [flake8 errors](https://github.com/glue-viz/glue-astronomy/runs/8276901571?check_suite_focus=true) seem to be the only remaining failures.

2022-09-12 13:33 UTC, dhomeier commented on glue_astronomy/translators/spectral_cube.py
> +from spectral_cube.spectral_cube import BaseSpectralCube, SpectralCube, VaryingResolutionSpectralCube
```suggestion
from spectral_cube import BooleanArrayMask
from spectral_cube.spectral_cube import BaseSpectralCube, SpectralCube, VaryingResolutionSpectralCube
```

2022-09-13 11:51 UTC, dhomeier commented on glue_astronomy/translators/spectral_cube.py
> +                                 beams=data_or_subset.meta['beams'])
```suggestion

data_translator(SpectralCube)(SpectralCubeHandler)
data_translator(DaskSpectralCube)(SpectralCubeHandler)


@data_translator(VaryingResolutionSpectralCube)
class VaryingResolutionSpectralCubeHandler(SpectralCubeHandler):

    def to_data(self, obj):
        data = super().to_data(obj)
        data.meta['beams'] = obj.beams
        return data

    def to_object(self, data_or_subset, attribute=None, cls=VaryingResolutionSpectralCube):
        return super().to_object(data_or_subset, attribute=attribute, cls=cls,
                                 beams=data_or_subset.meta['beams'])

```
E305

2022-09-13 11:51 UTC, dhomeier commented on glue_astronomy/translators/spectral_cube.py
> +from spectral_cube.spectral_cube import BaseSpectralCube, SpectralCube, VaryingResolutionSpectralCube
```suggestion
from spectral_cube.spectral_cube import (BaseSpectralCube, SpectralCube, 
                                         VaryingResolutionSpectralCube)
```
E501

2022-09-13 11:55 UTC, dhomeier commented on glue_astronomy/translators/spectral_cube.py
> +from spectral_cube.spectral_cube import (BaseSpectralCube, SpectralCube,
```suggestion
from spectral_cube.spectral_cube import (BaseSpectralCube, SpectralCube,
```

2022-09-20 14:24 UTC, dhomeier commented
@keflavich with the codestyle fixed and all tests passing, this could in principle be merged, if a changelog entry is added. Tests for the new formats would be nice as well, of course, but the main point I am wondering about is whether the translator provides enough functionality to be useful at this point.
I light of your initial comment how to subset the `beams`, from what I can see in this implementation `obj.beams` are exclusively stored in `data.meta['beams']`. This should round-trip correctly, but for further work (like taking subsets) it might be preferable to store them in `data` components? I am not familiar with the details of the various `SpectralCube` subclasses, so can't say what is really required here.
It should be OK to merge this PR as a first step towards full support, but I am also open to leave this open until it provides more complete functionality.

2022-09-20 14:55 UTC, keflavich commented
I don't understand enough about `data` components to know if they are the right place to store beams.


I'd be in favor of merging this now and opening new issues for additional functionality.

2022-09-20 15:13 UTC, dhomeier commented
And I don't know enough about beams... but basically every actual data object in glue is a `Component`, so this is probably the right approach to deal with this eventually.
But I agree we can merge now and work on the implementation details in a follow-up.
Could you add a description of those additional classes that can be loaded now to the `0.5.1 (unreleased)` section of the changelog? Thanks!

2022-09-23 12:15 UTC, astrofrog approved these changes
If we have information about the beam size in each pixel it could be stored as a component, otherwise it will need to be stored in ``.meta``. I think this is fine as-is - I would have liked to see a test included here for the new functionality but I also won't object if this is merged and tests are added later.

2022-09-24 12:29 UTC, merged