Return NDData for GWCS
glue-viz/glue-astronomy pull request #58
Opened 2021-11-29 19:51 UTC by pllim

## Description

Return NDData for GWCS instead of crashing in CCDData.

This works around astropy/astropy#11727 and is a hacky version of #38.

2021-12-02 16:42 UTC, astrofrog requested changes

2021-12-02 16:42 UTC, astrofrog commented on glue_astronomy/translators/ccddata.py
> +            has_gwcs = True
I think this is not a general enough name as there might be other non-GWCS APE 14 WCSes. I think it would be better to special case ``has_fitswcs`` in the first clause.

2021-12-02 17:33 UTC, pllim commented on glue_astronomy/translators/ccddata.py
> +            has_gwcs = True
Done. Looks good now?

2021-12-07 14:56 UTC, astrofrog requested changes
Looks good to me but the test failure is related - it might just be a case of updating the test?

2021-12-07 22:13 UTC, pllim commented
Re: Test failure -- I forgot to handle the case for `wcs = None` in a backward compatible way. The tests should pass now. Good catch and thanks for review!

2021-12-07 22:19 UTC, pllim commented
`casa` job failure is unrelated.

2021-12-07 22:25 UTC, astrofrog approved these changes

2021-12-07 22:25 UTC, merged