MNT: Modernize packaging, etc
glue-viz/glue-astronomy pull request #64
Opened 2022-02-23 18:36 UTC by pllim

I could not run tests locally, then I realized the packaging state of this package is way outdated. This pull request is to:

* Modernize packaging.
* Turn unhandled warnings into exceptions.
* Update test matrix.
* Fix test package data.
* Handle test warnings.

2022-02-23 18:40 UTC, pllim commented on .gitignore
> -glue/tests/htmlcov
Copy paste oversight?

2022-02-23 18:40 UTC, pllim commented on .readthedocs.yml
> +  fail_on_warning: true
You can set up RTD PR builder here using this setting and turn off sphinx builds on Azure.

2022-02-23 18:40 UTC, pllim commented on azure-pipelines.yml
>      - linux: py36-test-casa
You should really drop Python 3.6. I would have done it, except I don't know what CASA is doing there.

2022-02-23 18:40 UTC, pllim commented on setup.cfg
> -doctest_plug = enabled
Seems like you wanted to use `pytest-doctestplus` here but had a typo? Anyway, does not appear that you have any doctest right now but does not hurt to keep this in case you want to add doctest in the future.

2022-02-23 18:57 UTC, pllim commented
@dhomeier , this PR should be uncontroversial?

2022-02-24 16:02 UTC, astrofrog approved these changes
Looks great, thanks!

2022-02-24 16:02 UTC, astrofrog commented
I'll investigate the CASA failures separately

2022-02-24 16:02 UTC, merged

2022-02-24 19:55 UTC, dhomeier requested changes
Thanks for the reorganisation! I'd take your word for it, but haven't had anything to do with this package until last week, so perhaps give the updated CASA tests a try and then have a second pair of eyes on it.

2022-02-24 19:55 UTC, dhomeier commented on azure-pipelines.yml
>      - linux: py36-test-casa
```suggestion
```
CASATOOLS has wheels for py38, so should be no problem to move to that.

2022-02-24 19:55 UTC, dhomeier commented on azure-pipelines.yml
>      - linux: py38-test
```suggestion
    - linux: py38-test-casa
```

2022-02-24 19:55 UTC, dhomeier commented on azure-pipelines.yml
>      - macos: py38-test
```suggestion
    - windows: py37-test
    - macos: py38-test-casa
```

2022-02-24 19:56 UTC, pllim commented
Whoops, @dhomeier , this PR was already merged.

2022-02-24 19:58 UTC, dhomeier commented
Ah, seems the second pair of eyes was already faster than the first! Should not keep my review tabs open over night!

2022-02-24 23:14 UTC, dhomeier commented on glue_astronomy/io/spectral_cube/tests/test_spectral_cube.py
> +    assert is_spectral_cube(get_pkg_data_filename('data/cube_3d.image'))
Unfortunately that's the one that has broken the previously skipped casa-test, since `cube_3d.image` is a directory, which is supported by `read_spectral_cube`, but not `get_pkg_data_filename`. :(

2022-02-24 23:24 UTC, pllim commented on glue_astronomy/io/spectral_cube/tests/test_spectral_cube.py
> +    assert is_spectral_cube(get_pkg_data_filename('data/cube_3d.image'))
Whoops... sorry!

Should have used https://github.com/astropy/astropy/blob/179fa5fe1a97aaaa43e9d87d44eb366db454a396/astropy/utils/data.py#L892 instead. If you don't open a PR to fix this, I'll try to open one tomorrow when I get the chance.

2022-02-25 00:57 UTC, pllim commented on glue_astronomy/io/spectral_cube/tests/test_spectral_cube.py
> +    assert is_spectral_cube(get_pkg_data_filename('data/cube_3d.image'))
See astrofrog/glue-astronomy#1