translator for specreduce Trace objects
glue-viz/glue-astronomy pull request #72
Opened 2022-07-20 19:47 UTC by kecnry

This PR implements a new translator for [specreduce Trace objects](https://specreduce.readthedocs.io/en/latest/#module-specreduce.tracing).  In doing so, it adds specreduce as a dependency.  In order to round-trip and retrieve the same underyling Trace object (instead of always having to export to an `ArrayTrace`), this currently saves a copy of the input Trace object in the `meta` of the glue `Data` object.  If this is not preferred, we could create an `ArrayTrace` from the glue `Data` object, but we'll likely still need to attach an instance or reference to the input data.

2022-07-22 17:12 UTC, dhomeier commented
Do you think you could set up a test for this with a basic example `Data` set?

2022-07-26 13:24 UTC, dhomeier commented
Thanks for this contribution, this looks all quite good to me, although I am not familiar enough with the `Trace` format to say if this is the best possible implementation.
It certainly deserves a changelog entry as well, perhaps under `0.5.0 (unreleased)` for a new feature.

The main points I see remaining to be settled are
1. Adding `specreduce` to requirements; with `specutils` and `spectral-cube` already runtime dependencies and `specreduce` now an Astropy-coordinated package as well, I don't see much problems with that.
2. As you mentioned, adding the full trace to the `meta` data might be controversial. As I see it at the moment you are storing a full copy in `data.meta['Trace']`, while `data.meta['Trace'].trace` is at the same time kept in `data.y` (this might additionally be checked in the tests BTW). Wondering if it would be preferable to strip the `trace` itself from the `meta` copy and add it back in later in `to_object` to save some space, but I have no idea if it's worth the effort at all for typical sizes of these objects – I guess they are usually (n-1)-D, so not that large? Possibly there is not even a real memory impact if this is a shallow copy.

Leaving those open for discussion with @astrofrog.

2022-07-26 13:29 UTC, dhomeier commented on glue_astronomy/translators/tests/test_trace.py
> +    assert isinstance(data, Data)
```suggestion
    assert isinstance(data, Data)
    assert data['y'] == trace.trace
```
Hope I got that right, not sure if it's worth also checking the (shape of) `data['x']`

2022-07-29 18:37 UTC, eteq requested changes
I agree with @dhomeier that the dependency doesn't seem a big deal given the status of `specreduce` now.

I also agree that the memory impact is not serious given that, from my read of the internals of `Trace` and its sub-classes, both `obj.trace` and `obj.image`  are references not copies, and this is just carrying along those references.  As long as `glue` itself does not do any copying later on down the line this is probably "free".

2022-07-29 18:37 UTC, eteq commented on glue_astronomy/translators/trace.py
> +        data = Data(x=obj.image[0], y=obj.trace)
This is implicitly assuming that the 0th dimension is the "spectral"/"x" dimension.  I think that's also what `specreduce` is doing, so that's probably fine right now.  But I think it would be better if this is a property of the `Trace` object that indicates which is the "x" axis.

Maybe I should create an issue in specreduce about this and you can just add a "TODO: change when issue #xxx is addressed" or something?

2022-07-29 18:37 UTC, eteq commented on glue_astronomy/translators/trace.py
> +        return data.meta['Trace']
This worries me, because it is completely ignoring what's actually in the `data` object itself. I think that's counter-intuitive because a likely eventual workflow is to *change* the `y` trace by hand, which is probably most naturally done in glue.

So I would suggest the following:
1. If there's some way that glue data objects can flag "have been modified since created", only do the next step if that one is true.
2. Do something like:
```suggestion
        data.meta['Trace'].trace = data.y
        return data.meta['Trace']
```

Now this *does* introduce an assymetry between x and y.  But for a trace I think that makes sense.

Regardless, I think either in `to_object` or the top-level class, the docstring should be explcit about whether it gets data from glue to create the object.

2022-07-29 18:38 UTC, eteq commented
(Oh, and my "If there's some way that glue data objects can flag "have been modified since created", only do the next step if that one is true." comment could use some insight from @astrofrog if @dhomeier doesn't know the answer!)

2022-07-29 19:09 UTC, kecnry commented on glue_astronomy/translators/trace.py
> +        data = Data(x=obj.image[0], y=obj.trace)
Yes, there are some places in specreduce with general code to handle arbitrary "dispersion_axis", other parts where it's fixed at 0 but stored, and others where it's just assumed to be 0.  I agree that this is a specreduce issue that needs to be addressed consistently across all methods, and then generalize back here when that is supported.

2022-07-29 19:15 UTC, kecnry commented on glue_astronomy/translators/trace.py
> +        return data.meta['Trace']
I like this idea.  We can even include a check to make sure that `x` has not changed and that `y` is the correct length.  In cases where `y` has changed, we'll probably want to return an `ArrayTrace` with the modified `trace.y`.  For example: if the input trace object is a `FlatTrace`, but then the underlying data is modified once in glue, it no longer (necessarily) makes sense to return another `FlatTrace` object, right?

In theory, I don't see why `Trace` _needs_ the input image, it's just convenient to have attached, so if we can make that more flexible on the specreduce end, then we might be able to rebuild the object from scratch instead of relying on these references.  But I think in cases where the data isn't modified, it is nice to roundtrip and return the same type of trace, which at least involves storing some more information than the arrays themselves.

2022-07-29 20:02 UTC, kecnry commented on glue_astronomy/translators/trace.py
> +        return data.meta['Trace']
Update: I now check to see if the "y"-component matches the trace, and if not, create a new `ArrayTrace` object with the same image.  It turns out that glue does not allow changing the shape of data components, so there is no need for any checks on the lengths, but I do raise an error if the "x"-component no longer matches the dispersion axis of the image.

2022-08-01 11:08 UTC, dhomeier commented on glue_astronomy/translators/trace.py
> +        return data.meta['Trace']
> I also agree that the memory impact is not serious given that, from my read of the internals of `Trace` and its sub-classes, both `obj.trace` and `obj.image` are references not copies, and this is just carrying along those references. As long as `glue` itself does not do any copying later on down the line this is probably "free".

Any data component initialising or being added to a `data` object is processed by `Component.autotyped()`, which will typically involve `np.asarray(data)` and potentially other re-casting operations. So for most `ndarray` inputs there will probably be no actual copying, but even if, this only involves `obj.trace`. The `meta` reference is just an `OrderedDict` item.

> 1. If there's some way that glue data objects can flag "have been modified since created", only do the next step if that one is true.

Wondering if the callback mechanism might be used for this, although I do not see an example where this is applied in a `Data` component so far, apart from the use in `_update_world_components`.

2022-08-11 20:01 UTC, kecnry commented on glue_astronomy/translators/trace.py
> +        data = Data(x=obj.image[0], y=obj.trace)
That's a good point, I removed the x-component entirely and that still seems to do what is needed (without needing to worry or document anything about the dispersion axes).  Please check to see if this is what you had in mind or if you can think of any scenario this wouldn't work.

2022-08-12 16:37 UTC, dhomeier commented on glue_astronomy/translators/trace.py
> +        data = Data(x=obj.image[0], y=obj.trace)
Thanks; I think this is the most intuitive structure. About potential use scenarios I cannot say much, but in any case if you needed any of the actual image data, you'd still have access through `data.meta['Trace']`.
Could you rebase; this will hopefully fix the previous test failures?

2022-08-12 16:41 UTC, kecnry commented on glue_astronomy/translators/trace.py
> +        data = Data(x=obj.image[0], y=obj.trace)
rebased, but I don't have permissions to rerun the CI workflows.  Thanks!

2022-08-12 17:00 UTC, dhomeier requested changes
Apart from the minor style comments this should be good to go, thanks again!

@eteq I think your change requests are adequately addressed with this?
@astrofrog the only potentially contentious issue I see remaining is the `specreduce` dependency, but we had a clear majority in favour of that.

2022-08-12 17:00 UTC, dhomeier commented on glue_astronomy/translators/trace.py
> +            raise NotImplementedError("cannot convert subset to Trace object")
```suggestion
            raise NotImplementedError("Cannot convert subset to Trace object.")
```
sp

2022-08-12 17:00 UTC, dhomeier commented on glue_astronomy/translators/trace.py
> +            raise TypeError("data is not of a valid specreduce Trace object")
`data is not a valid...` or `data is not an instance of a valid...`?

2022-08-12 17:44 UTC, dhomeier approved these changes

2022-08-12 17:55 UTC, dhomeier approved these changes

2022-08-12 17:59 UTC, dhomeier commented
Oh, one last thing: please add a changelog entry, and change the current section heading to `0.5.0 (unreleased)`! :)

2022-08-12 19:56 UTC, dhomeier commented
Successful [test run](https://github.com/glue-viz/glue-astronomy/actions/runs/2848264922), so considering the last commit a `[ci skip]`.

2022-08-17 17:07 UTC, merged

2022-08-17 18:41 UTC, eteq commented
sorry I didn't get back to this sooner, by a a post-hoc "yes this is good, thanks!"