Adding support for uncertainty extraction to NDDataArray
glue-viz/glue-astronomy pull request #86
Opened 2023-02-27 19:04 UTC by bmorris3

In #81, I added translators for objects in `astropy.nddata`. In this PR, I add support for extracting uncertainties from glue `Data` objects and translating them into the `uncertainty` attr in `NDDataArray` objects. This was missing in the previous PR, but should have been there.

2023-02-27 20:48 UTC, pllim commented on glue_astronomy/translators/nddata.py
> +        ):
```suggestion
        if isinstance(data.coords, (WCS, BaseHighLevelWCS, SpectralCoordinates)):
```

2023-02-27 20:50 UTC, pllim commented on glue_astronomy/translators/nddata.py
> +                attribute = 'flux'
```suggestion
            for desired_label in ('data', 'flux'):
                if desired_label in component_labels:
                    attribute = desired_label
                    break
```

2023-02-27 20:51 UTC, pllim commented
CI failures appear related.

2023-02-28 18:37 UTC, pllim approved these changes

2023-02-28 21:01 UTC, dhomeier commented
I see. Would it make sense to have `to_data` convert other types with `represent_as(StdDevUncertainty)` then? That's probably a bit double-sided, as other applications may have use for the original forms, even if jdaviz does not a this point.
But otherwise I think it should check for the correct type on input, as the present implementation would e.g. silently interpret an `InverseVariance` as `StdDevUncertainty` and return it as such.

2023-03-01 14:22 UTC, bmorris3 commented
Good idea @dhomeier! Implemented in https://github.com/glue-viz/glue-astronomy/pull/86/commits/91d8dbc8989871182d358dbd5fd46ccc7e29cdc2.

2023-03-01 15:18 UTC, dhomeier requested changes
Great, thank! I'd still add the tests for the other input types.

2023-03-01 15:18 UTC, dhomeier commented on glue_astronomy/translators/tests/test_nddata.py
> +    assert_equal(spec_new.uncertainty.array, uncertainty.array)
```suggestion
@pytest.mark.parametrize('uncertainty_type', (StdDevUncertainty, VarianceUncertainty, InverseVariance))
def test_nddata_uncertainty(uncertainty_type):
    data = [[2, 3], [4, 5]] * u.Jy
    uncertainty = uncertainty_type(np.ones_like(data.value))
    spec = NDDataArray(
        data=data,
        uncertainty=uncertainty
    )
    data_collection = DataCollection()
    data_collection['data'] = spec

    data = data_collection['data']
    spec_new = data.get_object(NDDataArray)
    assert isinstance(spec_new.uncertainty, StdDevUncertainty)
    if  isinstance(uncertainty, StdDevUncertainty):
        assert_equal(spec_new.uncertainty.array, uncertainty.array)
    else:
        assert_equal(spec_new.uncertainty.array, uncertainty.represent_as(StdDevUncertainty).array)
```

2023-03-01 15:23 UTC, dhomeier commented
Will need imports for the other uncertainties; also we may have to compare to `spec.uncertainty` since that should have the correct units set (not sure if `represent_as` will transform it correctly otherwise).

2023-03-01 15:38 UTC, bmorris3 commented
@dhomeier Done and passing 💯

2023-03-01 15:44 UTC, dhomeier approved these changes

2023-03-01 18:06 UTC, bmorris3 commented
@dhomeier Would you consider this a bugfix, for soon release? We will use it downstream in https://github.com/spacetelescope/jdaviz/pull/2039.

2023-03-02 11:08 UTC, astrofrog approved these changes
Looks good to me!

2023-03-02 11:08 UTC, merged