bugfix for Spectrum1D translator with only spectral axes
glue-viz/glue-astronomy pull request #88
Opened 2023-03-06 19:53 UTC by bmorris3

The glue-astronomy translator generates glue `Data` objets from `Spectrum1D` with special treatment of the WCS coordinates. The current translator only produces a coordinate via `SpectralCoordinates` in the case where there's:

1. a 1D spectrum with 1D fluxes
2. WCS with one world dimension
3. *and* the WCS is an instance of `gwcs.WCS`. 

I'm working with a use-case (https://github.com/spacetelescope/jdaviz/pull/2039) with a single non-gwcs spectral axis. In this PR, I've simply allowed non-gwcs axes to pass through if it is clearly marked as a spectral axis, and meets criteria 1 and 2.

2023-03-14 14:34 UTC, dhomeier commented
Thanks for the PR, that functionality should definitely be supported. I was and still am concerned about the different treatment for the various data/wcs cases. Currently these cases are handled as
1. >1D flux (`spectrum.data`), >1D WCS: `data.coords = spectrum.wcs` (no further treatment).
2. >1D flux, 1D WCS: `data.coords = PaddedSpectrumWCS()` (custom expansion of spectral axis).
3. 1D flux, 1D WCS: `data.coords = spectrum.wcs` (no further treatment).
4. 1D flux, 1D GWCS: `data.coords = SpectralCoordinates()` (GWCS constructed from given `spectral_axis`).

So in case 4 `coords` directly provide a `SpectralCoordinates` object, while in 2 they return a `PaddedSpectrumWCS` containing `SpectralCoordinates` in its first element. They all should also provide `pixel_to_world_values`, while case 2 in addition provides `pixel_to_world`. Case 3 with the present changes would follow case 4, but its WCS could in fact just as well be used to construct a `PaddedSpectrumWCS` – with the padding of course not really necessary here, but offering all the functionality of case 2. There is a point for analogy to 4, both being fully 1D, but as both 2 and 3 are FITS WCS, it might also make sense to treat them as much alike as possible.

2023-03-14 15:20 UTC, bmorris3 commented
My understanding is that glue translators exist to get common domain-specific data structures constructed from glue-specific data structures. I'm not aware of uses for `PaddedSpectrumWCS` outside of glue-based applications, since this object is only a workaround to support limitations of `Data.coords` and ND spectra, as the source comments indicate:

https://github.com/glue-viz/glue-astronomy/blob/b5f2bf021c6665dcb134495ad02d3da3bd07c920/glue_astronomy/translators/spectrum1d.py#L37-L39

A search of all GitHub shows that it's only used within glue-astronomy and jdaviz. I don't think many/any users will benefit from translating to this glue-specific data structure.

2023-03-14 18:07 UTC, dhomeier requested changes
Changing the 1D GWCS case seems to break a number of tests, not sure if `glue.core.coordinate_helpers` could be updated to deal with it, but at this point better not to touch it. The rest passes with jdaviz main (probably not surprising since `SpectralCoordinates` was not available for 1D WCS either way.

2023-03-15 14:38 UTC, pllim commented
Re: PaddedSpectrumWCS

I agree this should not be the norm. I would love that everyone not use it at all if we had that option.

2023-03-15 14:48 UTC, dhomeier commented
You mean have glue just work with 1D spectral WCS for higher-dimensional data?
I guess that would be desirable, but outside of glue-astronomy.
How do you think about the use/availability of High Level WCS within `coords`?

2023-03-15 15:13 UTC, pllim commented
If you are asking me, I am not sure. I don't deal with spectra that often. If `data.coords` could be completely APE 14 compatible, that would be the best but then again I am not sure if APE 14 alone is sufficient for all the spectra requirements, if I remember some past conversations in other repos correctly. Would have to rope in people like Tom R, Stuart M, and Adam G for that conversation.

2023-03-15 19:39 UTC, dhomeier approved these changes
Thanks; looks good to me now if it is good for the jdaviz task.
Just pinging @astrofrog for comments on the APE-14/`PaddedSpectrumWCS` questions.

2023-03-16 11:47 UTC, astrofrog commented
I think glue should strictly follow APE 14 (and it should currently do that). I think the padded class is needed because specutils is giving a WCS which has different dimensionality to the data? (On phone so can't check)

2023-03-16 13:43 UTC, dhomeier commented
Yes, `PaddedSpectrumWCS` is needed for >1D flux; it is not needed for the 1D flux array here, but would make the interface more similar to the multi-D case and provide high-level WCS functionality that `SpectralCoordinates(spectral_axis)` does not.

2023-03-17 14:06 UTC, bmorris3 commented
> I think the padded class is needed because specutils is giving a WCS which has different dimensionality to the data? (On phone so can't check)

That's right. I think the remaining clarification needed here from @astrofrog is what type of coordinate object should be returned by `glue-astronomy`. `PaddedSpectrumWCS` provides compatibility between specutils and glue, which have different requirements for the number of specified coordinate dimensions. I'm advocating for a translator that returns the coordinates required for specutils, rather than glue.

2023-03-20 22:42 UTC, astrofrog commented on glue_astronomy/translators/spectrum1d.py
> +        if (obj.flux.ndim > 1 or isinstance(obj.wcs, WCS)) and obj.wcs.world_n_dim == 1:
Why do we need to use PaddedSpectrumWCS in the case of a 1D FITS WCS? Can we not just use the WCS directly as the coords object then?

2023-03-20 22:42 UTC, astrofrog commented on glue_astronomy/translators/spectrum1d.py
>              data = Data(coords=SpectralCoordinates(obj.spectral_axis))
Maybe beyond the scope here but note that SpectralCoordinates pre-dates the adoption of APE 14 by glue and it may actually be possible to just use the wcs object directly in this case? (even if GWCS)

2023-03-21 00:55 UTC, dhomeier commented on glue_astronomy/translators/spectrum1d.py
> +        if (obj.flux.ndim > 1 or isinstance(obj.wcs, WCS)) and obj.wcs.world_n_dim == 1:
That would be the status quo, but I think there is, at least no easily identified, method to return a  `SpectralCoordinates` object from the WCS, which was at the origin of this PR.
If there is, maybe it just needs to be documented and all those cases (including the GWCS one below) could be treated consistently.

2023-03-21 07:23 UTC, astrofrog commented on glue_astronomy/translators/spectrum1d.py
> +        if (obj.flux.ndim > 1 or isinstance(obj.wcs, WCS)) and obj.wcs.world_n_dim == 1:
WCS.pixel_to_world should return a SpectralCoordinates object for spectral WCS - does it not work?

2023-03-21 14:27 UTC, bmorris3 commented on glue_astronomy/translators/spectrum1d.py
> +        if (obj.flux.ndim > 1 or isinstance(obj.wcs, WCS)) and obj.wcs.world_n_dim == 1:
I'm not sure I follow – `obj.wcs` in this example is from `astropy` or `gwcs`. Are you referring to `SpectralCoordinates` in `glue-astronomy` [here](https://github.com/glue-viz/glue-astronomy/blob/b5f2bf021c6665dcb134495ad02d3da3bd07c920/glue_astronomy/spectral_coordinates.py#L9)?

2023-10-24 09:47 UTC, astrofrog commented
@bmorris3 - just to check, do you have any thoughts on my previous comment? Is this PR still needed?

2023-10-24 09:47 UTC, astrofrog reviewed
@bmorris3 - just to check, do you have any thoughts on my previous comment? Is this PR still needed?

2023-10-24 14:56 UTC, bmorris3 commented
I think what's on `main` now is sufficient. Closing.

2023-10-24 14:56 UTC, closed without merging