FEAT: Support AstropyRegionsHandler().to_object() direct call
glue-viz/glue-astronomy pull request #93
Opened 2023-06-06 20:31 UTC by pllim

## Description

There is a need for Jdaviz to be able to call the translator code directly via `AstropyRegionsHandler().to_object()`. This is useful for spatial region translations where we pass in the subset state directly internally and there is really no need to access `subset.data`. This blocks:

* https://github.com/spacetelescope/jdaviz/pull/2240

cc @dhomeier or @astrofrog

2023-06-06 20:32 UTC, pllim commented on glue_astronomy/translators/regions.py
> +GLUE_LT_1_11 = Version(glue_version) < Version('1.11')
@dhomeier , I also cleaning up the version check here, as discussed in https://github.com/glue-viz/glue-astronomy/pull/92#issuecomment-1572486547 . True annulus ROI support wasn't added till glue-core 1.11.

2023-06-12 18:16 UTC, pllim commented
There might be a cleaner way. I have to think more.

2023-06-15 14:01 UTC, astrofrog requested changes
This seems sensible to me - aside from a suggested API change. I'm ok with having the helper function be public API, but curious what the use case is compared to using the regular translator API in glue?

2023-06-15 15:16 UTC, pllim commented on glue_astronomy/translators/regions.py
> +def roi_subset_state_to_spatial(subset_state, to_sky=False):
I renamed it. Thanks for the review!

2023-06-16 10:55 UTC, astrofrog approved these changes

2023-06-16 10:55 UTC, merged