allow override of wcs when computing sky region in roi_subset_state_to_region
glue-viz/glue-astronomy pull request #96
Opened 2023-10-06 03:30 UTC by cshanahan1

In JDaviz (Cubeviz, specifically), sometimes subsets don't contain spatial wcs information in subset.xatt.coords, which is what is used for the pixel-to-sky conversion in `roi_subset_state_to_region`. To fix this issue, this PR adds the option to provide a different WCS for the conversion, which will override anything in `.coords`. 

(See https://github.com/spacetelescope/jdaviz/pull/2496)

2023-10-10 18:28 UTC, pllim requested changes

2023-10-10 18:28 UTC, pllim commented on glue_astronomy/translators/regions.py
> +def roi_subset_state_to_region(subset_state, to_sky=False, override_wcs=None):
```suggestion
def roi_subset_state_to_region(subset_state, to_sky=False):
```

2023-10-10 18:28 UTC, pllim commented on glue_astronomy/translators/regions.py
> +        The 2D glue Data object on which the range subset is defined.
This is wrong. Input is the subset state, not Data.

2023-10-10 18:28 UTC, pllim commented on glue_astronomy/translators/regions.py
> +        `astropy.wcs.WCS`, `gwcs.wcs.WCS`).
```suggestion
    to_sky: bool or `astropy.wcs.wcsapi.BaseHighLevelWCS`
        If `False`, pixel region is returned; otherwise sky region.
        If `True`, sky region will be computed using its parent's WCS.
        If a WCS is given, then that would be used instead of its parent's WCS
        (not recommended unless you know what you are doing).
```

2023-10-10 18:28 UTC, pllim commented on glue_astronomy/translators/regions.py
>      if to_sky:
```suggestion
```

2023-10-10 18:28 UTC, pllim commented on glue_astronomy/translators/regions.py
> +            reg = reg.to_sky(subset_state.xatt.parent.coords)
Do this at module-level imports:

```python
from astropy.wcs.wcsapi import BaseHighLevelWCS
```

Then this:

```suggestion
    if to_sky is True:
        reg = reg.to_sky(subset_state.xatt.parent.coords)
    elif isinstance(to_sky, BaseHighLevelWCS):
        reg = reg.to_sky(to_sky)
```

2023-10-10 20:27 UTC, cshanahan1 commented on glue_astronomy/translators/regions.py
> +def roi_subset_state_to_region(subset_state, to_sky=False, override_wcs=None):
done

2023-10-10 20:29 UTC, cshanahan1 commented on glue_astronomy/translators/regions.py
> +        `astropy.wcs.WCS`, `gwcs.wcs.WCS`).
i did something similar, how does that look?

2023-10-10 20:30 UTC, dhomeier requested changes
See comments on @pllim's comments; I am undecided whether re-using the existing kwarg this way is the best option...

And it would be good to test this, e.g. add to the end of `test_rectangular_roi` something like
```python
        self.data.coords = None
        with pytest.raises(**missing_wcs_error**):
            reg_sky = roi_subset_state_to_region(subset_state, to_sky=True)

        reg_sky = roi_subset_state_to_region(subset_state, to_sky=WCS_CELESTIAL)
        assert isinstance(reg_sky, RectangleSkyRegion)
```
Ideally this should perhaps even use two different WCS to make sure the user-provided is used; maybe one could instead pass in the second attempt a deepcopy of `WCS_CELESTIAL` modified to `wcs.wcs.ctype = ['GLON-CAR', 'GLAT-CAR']` and then check `reg_sky.wcs.ctype`...

2023-10-10 20:30 UTC, dhomeier commented on glue_astronomy/translators/regions.py
> +            reg = reg.to_sky(subset_state.xatt.parent.coords)
```suggestion
            reg = reg.to_sky(subset_state.xatt.parent.coords)
        elif to_sky:
            warnings.warn(f"Invalid input {to_sky} for ``to_sky``, "
                          "must be a valid WCS or set to `True`.",
                          UserWarning)
```
This is really for the change suggested by @pllim, but I cannot add suggestions on the suggestion...
But if we go that path, I think at that point (`not isinstance(to_sky, BaseHighLevelWCS)`) a sanity check is due, else it will appear to just silently ignore the `to_sky` input.

2023-10-10 20:45 UTC, cshanahan1 commented
Looks like I pushed some commits i made before seeing the most recent review comments - I added tests (and moved the old one that tested to_sky) and implemented @pllim of overloading to_sky to allow a new WCS to override anything attached to the subset.

2023-10-10 21:07 UTC, cshanahan1 commented on glue_astronomy/translators/regions.py
> +            reg = reg.to_sky(subset_state.xatt.parent.coords)
done

2023-10-10 21:13 UTC, dhomeier commented
Thanks, tests look good! I still would just like to see the exception for an invalid or missing wcs in `.coords` (the original issue above) tested.

2023-10-10 21:16 UTC, pllim commented
> Ideally this should perhaps even use two different WCS to make sure the user-provided is used

Let's not do that. Ideally, subset state should always refer to its parent. But in Cubeviz, we have to hack around the fact that cube ingested into Cubeviz somehow contains `.coords` without the original spatial WCS info (I cannot find that issue for cross-linking right now). So ideally when this problem is fixed properly, no one will ever have to pass in `to_sky` as a WCS ever again.

2023-10-10 21:22 UTC, pllim requested changes

2023-10-10 21:22 UTC, pllim commented on glue_astronomy/translators/regions.py
> +def roi_subset_state_to_region(subset_state, to_sky=False, override_wcs=None):
This is now not used anymore.
```suggestion
def roi_subset_state_to_region(subset_state, to_sky=False):
```

2023-10-10 21:22 UTC, pllim commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
Why was this removed? This is a completely different test.

2023-10-10 21:23 UTC, cshanahan1 commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
it was the only place that `roi_subset_state_to_region` was being tested, it seemed to me like it was just thrown into an existing test to make sure it worked. i moved it to its own test (just using circle instead of rectangle. i could test every shape but that seems like overkill)

2023-10-10 21:30 UTC, pllim commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
This one tests the rectangle. Your tests only have circles. I think it does not hurt to leave this in.

2023-10-10 21:31 UTC, pllim commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
While I understand your point above, I don't see why extra testing here would hurt. This is not an intensive operation.

2023-10-10 21:54 UTC, dhomeier commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
I agree the original test seemed thrown in a bit randomly, but if you really think Rectangle should be tested separately, perhaps do it properly indeed and `pytest.parametrize` over all supported ROI types (may indeed make sense, since the pixel_to_world transformations could be somewhat different under the hood).

2023-10-10 21:59 UTC, pllim commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
Well, as a maintainer, Derek has the final say here, so I guess we can remove it. 🤷

2023-10-11 12:43 UTC, pllim commented
Actually.... I just realized that you do not really need this PR, @cshanahan1 . Since you only use this function to compute pixel region, and then convert to sky region internally in Jdaviz, given that you want to keep both pixel and sky.

😬

2023-10-11 12:45 UTC, dhomeier commented on glue_astronomy/translators/tests/test_regions.py
> -        assert isinstance(reg_sky, RectangleSkyRegion)
Maybe `parametrize`ing the full `test_to_sky` over all ROI types with matching inputs and expected SkyRegions is a bit overkill indeed, so as a compromise you put that back in and add the same basic check to the tests for Polygonal, Elliptical and Point.

2023-10-11 12:48 UTC, dhomeier commented
> Let's not do that. Ideally, subset state should always refer to its parent. But in Cubeviz, we have to hack around the fact that cube ingested into Cubeviz somehow contains `.coords` without the original spatial WCS info

Thanks for the background – that explains why it all appears a bit hackish atm :D!
So you think no test for invalid input is needed either?

2023-10-11 12:49 UTC, pllim commented
I actually don't think this PR is needed at all. I am going to revisit https://github.com/spacetelescope/jdaviz/pull/2496 shortly.

2023-10-11 13:20 UTC, cshanahan1 commented
I parameterized the tests which is also something we can keep even if we don't move forward with allowing 'to_sky' to be a WCS.

2023-10-11 18:24 UTC, cshanahan1 commented
Closing this for now, doc + test changes we want to keep are in https://github.com/glue-viz/glue-astronomy/pull/97

2023-10-11 18:24 UTC, closed without merging